### ISSUE TITLE
To do is a bit unclear to me

### ISSUE THREAD

**Issue by rolandf** [st8st8/django-oscar-stripe-sca#4]
Hi,

this part is not clear to me could you please explain: 

`TODO

The sandbox and the tests have not been updated yet.`

What kind of update is pending/needed ?

Best regards,
Frederic

**Comment by st8st8** [comment]
Hey Frederic - thanks for your interest. 

This repo is (sort of) forked from django-oscar-stripe, with elements merged in from django-oscar-paypal to allow the new SCA flow.

As a result, there are elements lying around from django-oscar-stripe that have not been touched since I copied them over.  One is the unit tests, the other is the sandbox folder.  These are described in the readme for django-oscar-stripe:

https://github.com/django-oscar/django-oscar-stripe

Ideally, we would update the tests, and if we feel the sandbox is useful, update that too.

**Comment by rolandf** [comment]
Thank you.
